"""post title updated

Revision ID: 524e512475a9
Revises: 2e595e02d7dd
Create Date: 2024-07-11 21:21:05.175409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524e512475a9'
down_revision = '2e595e02d7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
